### ISSUE TITLE
Misc tweaks

### ISSUE THREAD

**Issue by nsbatra** [epirhandbook/handbookfiles#1]
@isaac-florence 
Just adding notes for tweaks (for whenever you get to them). Thank you!!

- documentation of get_data() - says to write "ALL" when in truth it only accepts "all". Either one is fine, just align.

- Could you have it say "Run get_data("all") to download all data" in the get_data() yellow box? 

- Likewise in the yellow box for download_book() can you have it state that it is downloading from Github, and instruct the user to run the command with empty parentheses (beginners won't realize that)?

- On that note, would it slow things down massively if the offline handbook was also a file internal to the package? 
I worry about someone just downloading the package and not realizing they needed to download the handbook before they lost internet access.

**Comment by isaac-florence** [comment]
Sorry to have only just seen this. 

I see you fixed the first point, thanks!

I am not 100% confident in the best way to do that (will learn and tweak) but have updated the docs for clarity about running with no arguments (I don't think beginners will know that default means empty so have changed that wording)

I think it would and also will likely flag some funky security concerns if downloading such a large HTML in an R package! Even though we're not publishing on CRAN I want to avoid doing stuff that wouldn't allow CRAN submission! Plus of course we'd need to update the package every time it gets tweaked whereas at least this will keep it somewhat live! When we have the handbook in multiple languages I will add in options to get the right language!
