### ISSUE TITLE
font for multilingualisation

### ISSUE THREAD

**Issue by babayoshihiko** [epirhandbook/handbookfiles#3]
I am translating EpiRHandbook to Japanese. But translators of many other languages are interested.

The current Rmd produces plots and maps using ggplot and tmap. This is OK with most Western languages, but may not output texts properly in non-ASCII languages, e.g. Chinese, Japanese and Korean in some cases. Setting font in a theme_* function often solves this issue. But the font family depends on OS.

Below is a sample notebook which works both on macOS and Windows:
http://babayoshihiko.ddns.net/EpiRHandbookBaba/gis.ja.nb.html

**Comment by jarvisc1** [comment]
Closing old issue
