### ISSUE TITLE
Problem with installing R Package of epirhandbook

### ISSUE THREAD

**Issue by arshahab76** [epirhandbook/handbookfiles#7]
Hello,

I am trying to install the R Package of epirhandbook from Github using the following command,

```{r}
library(pacman)
pacman::p_install_gh("appliedepi/epirhandbook")
```

I get the following message.

> The following packages were installed:
> epirhandbook
> Warning message:
> In pacman::p_install_gh("appliedepi/epirhandbook") : The following may have incorrect capitalization specification: epirhandbook

When i try to load the epirhandbook through this command:

```{r}
pacman::p_load(epirhandbook)
```
I get the following message:

> Warning messages:
> 1: package ‘epirhandbook’ is not available for this version of R
> A version of this package for your version of R might be available elsewhere, see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
> 2: In p_install(package, character.only = TRUE, ...) : 
> 3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘epirhandbook’
> 4: In pacman::p_load(epirhandbook) : Failed to install/load:
> epirhandbook

I am new to R and I am learning from the online resources how to use R for statistical analysis in public health. I wonder someone will tell me how to deal with the issue to be able to install "epirhandbook".

_Note. I have installed pacman library on RStudio. I have followed the steps recommended by the author of the package at https://epirhandbook.com/en/download-handbook-and-data.html_

Thank you in advance.

**Comment by jarvisc1** [comment]
Closing old issue
